version: '2'
services:
  db:
    container_name: mysqld
    image: mysql:5.7
    ports:
      - "3306:3306"
    env_file:
      - ./.env
  cache:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
  api:
    container_name: weather-csv-api
    image: weather-csv-api:v0.98
    env_file:
      - ./.env
    depends_on:
      - db
    ports:
      - "5000:5000"
networks:
  default:
    driver: bridge
    