apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::787080764332:role/eks-cluster20200215094123004700000005
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
    - rolearn: arn:aws:iam::787080764332:role/codebuild-role-weather-container-app
      username: system:codebuild
      groups:
        - system:masters